site_name: Lumino
site_url: https://lumino.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo:  assets/logo_lumino.png
    # icon: 
    #   logo: assets/lumino.ico

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Introducción: index.md
  # - Introducción: introduccion.md
  - Requisitos del Proyecto: requisitos.md
  - Diseño del Sistema: diseño.md
  - Implementación: implementacion.md
  - Pruebas: pruebas.md
  - Despliegue: despliegue.md
  - Manuales de Usuario: manuales.md
  - Mantenimiento y Actualización: mantenimiento.md
  - Conclusión y Futuro: conclusion.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - markmap:


