# site_name: My Docs
# site_url: https://mydocs.example
# theme:
#   name: material
#   font:
#     text: Merriweather Sans
#     code: Red Hat Mono
#   favicon: assets/lumino.ico
#   logo: 
#   # icon: 
#   #   logo: fontawesome/solid/d
#   palette:
#     # schema: slate
#     # primary: green
#     # accent: deep purple

#     # Dark Mode
#     - scheme: slate
#       toggle:
#         icon: material/weather-sunny
#         name: Dark mode
#       primary: green
#       accent: deep purple
    
#     # Dark Ligh
#     - scheme: default
#       toggle:
#         icon: material/weather-night
#         name: Light mode
#       primary: blue
#       accent: deep orange


# markdown_extensions:
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg

# nav:
#   # Inicio: index.md
#   # Introducción: index.md
#   # Requisitos del proyecto: index.md
#   # Diseño del Sistema: index.md
#   # Implementación: index.md
#   # Pruebas: index.md
#   # Despliegue: index.md
#   # Manuales de usuario: index.md
#   # Mantenimiento y Actualización: index.md
#   # Conclusión y Futuro: index.md

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#       line_spans: __span
#       pygments_lang_class: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences


site_name: Lumino Docs
site_url: https://lumino.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/lumino.ico
  logo: 
  # icon: 
  #   logo: fontawesome/solid/d
  #   palette:
  #     schema: slate
  #     primary: green
  #     accent: deep purple

  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Introducción: introduccion.md
  - Requisitos del Proyecto: requisitos.md
  - Diseño del Sistema: diseño.md
  - Implementación: implementacion.md
  - Pruebas: pruebas.md
  - Despliegue: despliegue.md
  - Manuales de Usuario: manuales.md
  - Mantenimiento y Actualización: mantenimiento.md
  - Conclusión y Futuro: conclusion.md

